version: "3.3"

services:
  db:
    image: mariadb:lts
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: firefly
      MYSQL_USER: firefly
      MYSQL_PASSWORD: firefly123
    volumes:
      - db:/var/lib/mysql

  app:
    image: fireflyiii/core:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      APP_KEY: base64:kHzL8VDowzPQAlWxKc8SxTO1YM6FcMJu
      APP_URL: https://firefly-app.koyeb.app
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: firefly
      DB_USERNAME: firefly
      DB_PASSWORD: firefly123
      STATIC_CRON_TOKEN: cronsegreto123
    volumes:
      - upload:/var/www/html/storage/upload

  cron:
    image: alpine
    depends_on:
      - app
    command: >
      sh -c "echo '0 3 * * * wget -qO- http://app:8080/api/v1/cron/cronsegreto123' \
            | crontab - && crond -f -L /dev/stdout"

volumes:
  db:
  upload:
